#!/usr/bin/env python3
"""Insert sample CW Germany airport markers into the map_data.db for testing.

This is an empty template so you can add new `Location` entries for the CW Germany map.

Usage:
  python add_cw_germany_markers.py [--replace]

Options:
  --replace   Delete existing location data before inserting samples

This script is intentionally lightweight and intended for development/testing only.
"""
from pathlib import Path
import argparse
import sys

scripts_dir = Path(__file__).parent
if str(scripts_dir) not in sys.path:
    sys.path.insert(0, str(scripts_dir))

from core.markers_database import MarkersDatabase, Location, Runway, MarkerType


def estimate_heading_from_name(name: str):
    """Estimate runway heading from runway name (e.g., '12/30' -> 120.0). Returns None if it cannot parse a numeric runway designation."""
    import re
    if not name:
        return None
    m = re.search(r"(\d{1,2})", name)
    if not m:
        return None
    try:
        num = int(m.group(1))
        return float(num * 10.0)
    except Exception:
        return None


def germany_samples():
    """Return a list of Location objects for CW Germany.

    Currently empty — add `Location(...)` entries to this list.

    Example (commented):

    # Location(
    #     name="Example Airport",
    #     latitude=52.0,
    #     longitude=13.0,
    #     marker_type=MarkerType.AIRPORT.value,
    #     icao="XXXX",
    #     iata="",
    #     elevation_m=100.0,
    #     runways=[Runway(name="09/27", length_m=2500, width_m=45, heading=None, surface="asphalt")],
    #     frequencies={"tower":"121.0 MHz"},
    #     country="Germany",
    #     tags=["civilian"],
    #     source="OurAirports / DCS-World MAP",
    #     map="CW Germany"
    # ),
    """

    samples = [
        Location(
            name="Adelsheim",
            latitude=49.4008,
            longitude=9.4036,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=232.0,
            runways=[Runway(name="05/23", length_m=800, width_m=20, heading=50.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "airfield"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Air racing Frankfurt",
            latitude=50.0379,
            longitude=8.5622,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=112.0,
            runways=[Runway(name="07/25", length_m=1200, width_m=30, heading=70.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "racing"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Air racing Koblenz",
            latitude=50.3569,
            longitude=7.5875,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=195.0,
            runways=[Runway(name="06/24", length_m=1000, width_m=25, heading=58.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "racing"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Air racing Lübeck",
            latitude=53.8053,
            longitude=10.7192,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDHL",
            iata="",
            elevation_m=16.0,
            runways=[Runway(name="07/25", length_m=2000, width_m=45, heading=72.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "racing"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Allstedt",
            latitude=51.3833,
            longitude=11.4333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=185.0,
            runways=[Runway(name="07/25", length_m=1000, width_m=30, heading=67.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airfield"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Bad Dürkheim",
            latitude=49.4667,
            longitude=8.1833,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDRF",
            iata="",
            elevation_m=109.0,
            runways=[Runway(name="08/26", length_m=830, width_m=18, heading=75.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "airfield"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Bindersleben (Erfurt)",
            latitude=50.9798,
            longitude=10.9581,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDE",
            iata="",
            elevation_m=316.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=45, heading=94.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["civilian", "airport"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Bitburg Air Base",
            latitude=49.9453,
            longitude=6.5650,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDRB",
            iata="",
            elevation_m=382.0,
            runways=[Runway(name="05/23", length_m=3050, width_m=45, heading=50.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "USAF"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Bornholm (Rønne)",
            latitude=55.0633,
            longitude=14.7596,
            marker_type=MarkerType.AIRPORT.value,
            icao="EKRN",
            iata="",
            elevation_m=52.0,
            runways=[Runway(name="11/29", length_m=2000, width_m=45, heading=110.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="Denmark",
            tags=["civilian", "airport"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Brand",
            latitude=51.9167,
            longitude=13.3167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=78.0,
            runways=[Runway(name="09/27", length_m=2400, width_m=40, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Brandis",
            latitude=51.3272,
            longitude=12.6089,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=127.0,
            runways=[Runway(name="08/26", length_m=2500, width_m=45, heading=82.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Braunschweig-Wolfsburg",
            latitude=52.3192,
            longitude=10.5564,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDVE",
            iata="",
            elevation_m=91.0,
            runways=[Runway(name="08/26", length_m=2040, width_m=45, heading=83.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "airport"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Bremen",
            latitude=53.0475,
            longitude=8.7867,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDW",
            iata="BRE",
            elevation_m=4.0,
            runways=[Runway(name="09/27", length_m=2034, width_m=45, heading=87.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "airport"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Briest",
            latitude=52.6667,
            longitude=12.4500,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=42.0,
            runways=[Runway(name="07/25", length_m=2500, width_m=60, heading=73.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Büchel Air Base",
            latitude=50.1739,
            longitude=7.0633,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETSB",
            iata="",
            elevation_m=469.0,
            runways=[Runway(name="03/21", length_m=3048, width_m=45, heading=27.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "nuclear"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Bückeburg Air Base",
            latitude=52.2786,
            longitude=9.0819,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETHB",
            iata="",
            elevation_m=70.0,
            runways=[Runway(name="08/26", length_m=1832, width_m=45, heading=80.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "army aviation"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Chojna Airfield",
            latitude=52.9644,
            longitude=14.4289,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=25.0,
            runways=[Runway(name="11/29", length_m=2500, width_m=60, heading=110.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="Poland",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Cochstedt Airport",
            latitude=51.8564,
            longitude=11.4203,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDBC",
            iata="",
            elevation_m=183.2,
            runways=[Runway(name="08/26", length_m=2495, width_m=45, heading=77.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "civilian", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Cologne Bonn Airport",
            latitude=50.8659,
            longitude=7.1427,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDK",
            iata="CGN",
            elevation_m=92.0,
            runways=[
                Runway(name="14L/32R", length_m=3815, width_m=60, heading=141.0, surface="asphalt"),
                Runway(name="06/24", length_m=2459, width_m=45, heading=60.0, surface="concrete"),
                Runway(name="14R/32L", length_m=1863, width_m=45, heading=141.0, surface="asphalt")
            ],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "international"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Damgarten Airfield",
            latitude=54.1514,
            longitude=12.4756,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=3.0,
            runways=[Runway(name="08/26", length_m=2500, width_m=60, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Dedelow Airfield",
            latitude=53.3378,
            longitude=13.9247,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=58.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Dessau Airfield",
            latitude=51.8314,
            longitude=12.1911,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDAD",
            iata="",
            elevation_m=61.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Düsseldorf Airport",
            latitude=51.2895,
            longitude=6.7668,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDL",
            iata="DUS",
            elevation_m=45.0,
            runways=[
                Runway(name="05L/23R", length_m=2700, width_m=45, heading=51.0, surface="asphalt"),
                Runway(name="05R/23L", length_m=3000, width_m=45, heading=51.0, surface="asphalt")
            ],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "international"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Falkenberg Airfield",
            latitude=53.3958,
            longitude=13.2781,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=82.0,
            runways=[Runway(name="08/26", length_m=2500, width_m=60, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Fassberg Air Base",
            latitude=52.9192,
            longitude=10.1856,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETHS",
            iata="",
            elevation_m=75.0,
            runways=[Runway(name="09/27", length_m=2430, width_m=45, heading=90.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Finow Air Base",
            latitude=52.8272,
            longitude=13.7178,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDAV",
            iata="",
            elevation_m=52.0,
            runways=[Runway(name="08/26", length_m=2500, width_m=60, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Frankfurt Main Airport",
            latitude=50.0379,
            longitude=8.5622,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDF",
            iata="FRA",
            elevation_m=111.0,
            runways=[
                Runway(name="07L/25R", length_m=4000, width_m=45, heading=70.0, surface="asphalt"),
                Runway(name="07C/25C", length_m=4000, width_m=60, heading=70.0, surface="concrete"),
                Runway(name="07R/25L", length_m=2800, width_m=45, heading=70.0, surface="asphalt")
            ],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "international"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Fritzlar Air Base",
            latitude=51.1146,
            longitude=9.2858,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETHF",
            iata="",
            elevation_m=214.0,
            runways=[Runway(name="09/27", length_m=2440, width_m=45, heading=90.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "army aviation"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Fulda-Jossa Airfield",
            latitude=50.5567,
            longitude=9.5117,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=340.0,
            runways=[Runway(name="09/27", length_m=800, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "gliding"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Gardelegen Airfield",
            latitude=52.5361,
            longitude=11.3922,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=46.0,
            runways=[Runway(name="08/26", length_m=2500, width_m=60, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        # BATCH 3 - Garz to Kiel
        Location(
            name="Garz",
            latitude=54.3117,
            longitude=13.3267,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=15.0,
            runways=[Runway(name="09/27", length_m=1200, width_m=30, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Gatow (Berlin)",
            latitude=52.4733,
            longitude=13.1417,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETUB",
            iata="",
            elevation_m=49.0,
            runways=[Runway(name="09/27", length_m=2064, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Berlin",
            tags=["military", "airbase", "RAF", "Berlin airlift"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Gelnhausen",
            latitude=50.2078,
            longitude=9.1656,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETGN",
            iata="",
            elevation_m=146.0,
            runways=[Runway(name="08/26", length_m=1830, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "US Army"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Giebelstadt",
            latitude=49.6483,
            longitude=9.9667,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETEU",
            iata="",
            elevation_m=287.0,
            runways=[Runway(name="06/24", length_m=1448, width_m=30, heading=60.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "US Army", "helicopter"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Gindbruchkippe",
            latitude=52.5833,
            longitude=11.4500,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=60.0,
            runways=[Runway(name="10/28", length_m=1400, width_m=30, heading=100.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Gross Mohrdorf",
            latitude=54.2167,
            longitude=13.0500,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=10.0,
            runways=[Runway(name="08/26", length_m=2200, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Gütersloh",
            latitude=51.9228,
            longitude=8.3063,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETUO",
            iata="GUT",
            elevation_m=75.0,
            runways=[Runway(name="09/27", length_m=2439, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "RAF"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Hamburg",
            latitude=53.6304,
            longitude=9.9882,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDH",
            iata="HAM",
            elevation_m=11.0,
            runways=[
                Runway(name="05/23", length_m=3666, width_m=45, heading=50.0, surface="concrete"),
                Runway(name="15/33", length_m=3250, width_m=45, heading=150.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "international", "major"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Hamburg Finkenwerder",
            latitude=53.5353,
            longitude=9.8356,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDHI",
            iata="",
            elevation_m=6.0,
            runways=[Runway(name="05/23", length_m=2265, width_m=45, heading=50.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "industrial", "Airbus"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Hannover",
            latitude=52.4611,
            longitude=9.6850,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDV",
            iata="HAJ",
            elevation_m=55.0,
            runways=[
                Runway(name="09L/27R", length_m=3800, width_m=45, heading=90.0, surface="concrete"),
                Runway(name="09R/27L", length_m=2340, width_m=45, heading=90.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "international", "major"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Hassfelde",
            latitude=52.8167,
            longitude=11.1833,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=35.0,
            runways=[Runway(name="09/27", length_m=1800, width_m=30, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Heidelberg Army Airfield",
            latitude=49.3933,
            longitude=8.6517,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETIE",
            iata="",
            elevation_m=98.0,
            runways=[Runway(name="09/27", length_m=1219, width_m=23, heading=90.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "US Army", "helicopter"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Herrenteich",
            latitude=53.7333,
            longitude=11.6167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=45.0,
            runways=[Runway(name="06/24", length_m=1600, width_m=30, heading=60.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Hildesheim",
            latitude=52.1756,
            longitude=9.9456,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDVM",
            iata="",
            elevation_m=88.0,
            runways=[Runway(name="07/25", length_m=2234, width_m=45, heading=70.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "British Army"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Hockenheim",
            latitude=49.3297,
            longitude=8.5347,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDGH",
            iata="",
            elevation_m=102.0,
            runways=[Runway(name="08/26", length_m=1355, width_m=30, heading=80.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "general aviation"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Holzdorf",
            latitude=51.7678,
            longitude=13.1672,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETSH",
            iata="",
            elevation_m=87.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Kammermark",
            latitude=53.3667,
            longitude=11.5333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=50.0,
            runways=[Runway(name="10/28", length_m=1500, width_m=30, heading=100.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Kastrup (Copenhagen)",
            latitude=55.6181,
            longitude=12.6561,
            marker_type=MarkerType.AIRPORT.value,
            icao="EKCH",
            iata="CPH",
            elevation_m=5.0,
            runways=[
                Runway(name="04L/22R", length_m=3600, width_m=45, heading=40.0, surface="concrete"),
                Runway(name="04R/22L", length_m=3300, width_m=45, heading=40.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="Denmark",
            tags=["civilian", "international", "major"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Kiel-Holtenau",
            latitude=54.3794,
            longitude=10.1453,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDHK",
            iata="KEL",
            elevation_m=31.0,
            runways=[Runway(name="08/26", length_m=2499, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "Luftwaffe", "naval"],
            source="DCS World",
            map="CW Germany"
        ),
        # BATCH 4 - Köthen to Obermehler-Schlotheim
        Location(
            name="Köthen",
            latitude=51.7211,
            longitude=11.9528,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDCK",
            iata="",
            elevation_m=93.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Laage",
            latitude=53.9182,
            longitude=12.2783,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETNL",
            iata="RLG",
            elevation_m=41.0,
            runways=[Runway(name="08/26", length_m=2500, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Landstuhl",
            latitude=49.4303,
            longitude=7.5653,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=300.0,
            runways=[Runway(name="08/26", length_m=1200, width_m=30, heading=80.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "US Army", "hospital"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Langenselbold",
            latitude=50.1667,
            longitude=9.0500,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=125.0,
            runways=[Runway(name="09/27", length_m=1100, width_m=25, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Lärz",
            latitude=53.4447,
            longitude=12.7156,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETNL",
            iata="",
            elevation_m=62.0,
            runways=[Runway(name="06/24", length_m=2500, width_m=60, heading=60.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Leipzig Mockau",
            latitude=51.4167,
            longitude=12.4333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=131.0,
            runways=[Runway(name="09/27", length_m=1800, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "historical"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Lübeck",
            latitude=53.8054,
            longitude=10.7192,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDHL",
            iata="LBC",
            elevation_m=16.0,
            runways=[Runway(name="07/25", length_m=2076, width_m=45, heading=70.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "regional"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Lüneburg",
            latitude=53.2486,
            longitude=10.4067,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=23.0,
            runways=[Runway(name="09/27", length_m=1200, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Mahlwinkel",
            latitude=52.0722,
            longitude=11.6333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=76.0,
            runways=[Runway(name="10/28", length_m=2500, width_m=60, heading=100.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Mainz Finthen",
            latitude=49.9675,
            longitude=8.1472,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDFZ",
            iata="",
            elevation_m=206.0,
            runways=[Runway(name="09/27", length_m=1738, width_m=30, heading=90.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "US Army", "civilian"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Marxwalde",
            latitude=52.6617,
            longitude=14.2333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=20.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Mendig",
            latitude=50.3661,
            longitude=7.3153,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETHC",
            iata="",
            elevation_m=191.0,
            runways=[Runway(name="08/26", length_m=2440, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "Belgian Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Merseburg",
            latitude=51.3633,
            longitude=11.9408,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=102.0,
            runways=[Runway(name="09/27", length_m=2000, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Neubrandenburg",
            latitude=53.6022,
            longitude=13.3061,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDBN",
            iata="FNB",
            elevation_m=70.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Neuruppin",
            latitude=52.9194,
            longitude=12.8056,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDBN",
            iata="",
            elevation_m=51.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Nordholz",
            latitude=53.7672,
            longitude=8.6585,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETMN",
            iata="",
            elevation_m=22.0,
            runways=[Runway(name="08/26", length_m=2440, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "Luftwaffe", "naval"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Northeim",
            latitude=51.7061,
            longitude=10.0194,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=124.0,
            runways=[Runway(name="09/27", length_m=1350, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Nörvenich",
            latitude=50.8311,
            longitude=6.6578,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETNN",
            iata="",
            elevation_m=118.0,
            runways=[Runway(name="07/25", length_m=2438, width_m=45, heading=70.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "Luftwaffe"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Ober-Morlen",
            latitude=50.3667,
            longitude=8.7167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=180.0,
            runways=[Runway(name="08/26", length_m=1100, width_m=25, heading=80.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Obermehler-Schlotheim",
            latitude=51.2667,
            longitude=10.6500,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=210.0,
            runways=[Runway(name="10/28", length_m=1800, width_m=40, heading=100.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military"],
            source="DCS World",
            map="CW Germany"
        ),
        # BATCH 5 - Oranienburg to Zweibrücken (Final ~43 airports)
        Location(
            name="Oranienburg",
            latitude=52.7550,
            longitude=13.2372,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=40.0,
            runways=[Runway(name="09/27", length_m=2000, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Parchim",
            latitude=53.4278,
            longitude=11.7833,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDOP",
            iata="SZW",
            elevation_m=49.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Peenemünde",
            latitude=54.1578,
            longitude=13.7742,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDCP",
            iata="PEF",
            elevation_m=5.0,
            runways=[Runway(name="09/27", length_m=2400, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "research", "V-2"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Perwenitz",
            latitude=52.6667,
            longitude=13.0167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=50.0,
            runways=[Runway(name="10/28", length_m=1600, width_m=30, heading=100.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Pferdsfeld",
            latitude=49.8667,
            longitude=7.4500,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDRP",
            iata="",
            elevation_m=400.0,
            runways=[Runway(name="09/27", length_m=1350, width_m=30, heading=90.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "US Army", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Pinnow",
            latitude=53.2167,
            longitude=13.7333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=15.0,
            runways=[Runway(name="08/26", length_m=2200, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Pottschutthöhe",
            latitude=52.4167,
            longitude=11.8333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=70.0,
            runways=[Runway(name="09/27", length_m=1500, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Ramstein",
            latitude=49.4369,
            longitude=7.6003,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETAR",
            iata="RMS",
            elevation_m=243.0,
            runways=[Runway(name="09/27", length_m=3200, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "USAF", "major"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Revinge",
            latitude=55.6833,
            longitude=13.4500,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=90.0,
            runways=[Runway(name="09/27", length_m=1800, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="Sweden",
            tags=["military", "airbase", "Swedish Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Rheine",
            latitude=52.2914,
            longitude=7.3969,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETHE",
            iata="",
            elevation_m=41.0,
            runways=[Runway(name="09/27", length_m=2440, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "Luftwaffe"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Rinteln",
            latitude=52.1667,
            longitude=9.0667,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=55.0,
            runways=[Runway(name="08/26", length_m=1200, width_m=30, heading=80.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "British Army"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Schkeuditz",
            latitude=51.4239,
            longitude=12.2369,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDP",
            iata="LEJ",
            elevation_m=131.0,
            runways=[
                Runway(name="08L/26R", length_m=3600, width_m=45, heading=80.0, surface="concrete"),
                Runway(name="08R/26L", length_m=2500, width_m=45, heading=80.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["civilian", "Leipzig Airport", "major"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Schönefeld",
            latitude=52.3800,
            longitude=13.5222,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDB",
            iata="SXF",
            elevation_m=48.0,
            runways=[
                Runway(name="07L/25R", length_m=3000, width_m=45, heading=70.0, surface="concrete"),
                Runway(name="07R/25L", length_m=3000, width_m=45, heading=70.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["civilian", "international", "East Berlin"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Schweinfurt",
            latitude=50.0408,
            longitude=10.2367,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=226.0,
            runways=[Runway(name="08/26", length_m=1525, width_m=30, heading=80.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "US Army"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Sembach",
            latitude=49.5028,
            longitude=7.8586,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETSH",
            iata="",
            elevation_m=309.0,
            runways=[Runway(name="09/27", length_m=2743, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "USAF"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Spangdahlem",
            latitude=49.9725,
            longitude=6.6925,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETAD",
            iata="SPM",
            elevation_m=356.0,
            runways=[Runway(name="05/23", length_m=3048, width_m=45, heading=50.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "USAF"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Sperenberg",
            latitude=52.1667,
            longitude=13.4167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=48.0,
            runways=[Runway(name="09/27", length_m=3000, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force", "strategic"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Sprendlingen",
            latitude=49.9167,
            longitude=8.3667,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=150.0,
            runways=[Runway(name="09/27", length_m=1100, width_m=25, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Stendal",
            latitude=52.6286,
            longitude=11.8186,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=43.0,
            runways=[Runway(name="09/27", length_m=2000, width_m=45, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Sturup",
            latitude=55.5303,
            longitude=13.3761,
            marker_type=MarkerType.AIRPORT.value,
            icao="ESMS",
            iata="MMX",
            elevation_m=72.0,
            runways=[Runway(name="17/35", length_m=2700, width_m=45, heading=170.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="Sweden",
            tags=["civilian", "regional", "Malmö"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Szczecin-Goleniow",
            latitude=53.5847,
            longitude=14.9022,
            marker_type=MarkerType.AIRPORT.value,
            icao="EPSC",
            iata="SZZ",
            elevation_m=45.0,
            runways=[Runway(name="13/31", length_m=2500, width_m=60, heading=130.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="Poland",
            tags=["civilian", "military", "international"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Tagra",
            latitude=52.7833,
            longitude=12.3167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=55.0,
            runways=[Runway(name="09/27", length_m=1600, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Tegel",
            latitude=52.5597,
            longitude=13.2877,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDT",
            iata="TXL",
            elevation_m=37.0,
            runways=[
                Runway(name="08L/26R", length_m=3021, width_m=46, heading=80.0, surface="concrete"),
                Runway(name="08R/26L", length_m=2428, width_m=46, heading=80.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="West Berlin",
            tags=["civilian", "international", "major", "West Berlin"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Tempelhof",
            latitude=52.4728,
            longitude=13.4039,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDDI",
            iata="THF",
            elevation_m=48.0,
            runways=[
                Runway(name="09L/27R", length_m=2094, width_m=46, heading=90.0, surface="concrete"),
                Runway(name="09R/27L", length_m=1840, width_m=46, heading=90.0, surface="concrete")
            ],
            frequencies={"tower": 120.0},
            country="West Berlin",
            tags=["military", "civilian", "USAF", "Berlin airlift", "historic"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Templin",
            latitude=53.1167,
            longitude=13.6667,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=55.0,
            runways=[Runway(name="09/27", length_m=1800, width_m=30, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Thürand",
            latitude=52.5500,
            longitude=12.7000,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=65.0,
            runways=[Runway(name="10/28", length_m=1500, width_m=30, heading=100.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Tutow",
            latitude=53.9233,
            longitude=13.2189,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDUW",
            iata="",
            elevation_m=6.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Uelzen",
            latitude=52.9839,
            longitude=10.4656,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDVU",
            iata="",
            elevation_m=47.0,
            runways=[Runway(name="08/26", length_m=1200, width_m=30, heading=80.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Uetersen",
            latitude=53.6472,
            longitude=9.7042,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDHE",
            iata="",
            elevation_m=10.0,
            runways=[Runway(name="06/24", length_m=1000, width_m=25, heading=60.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "general aviation"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Ummern",
            latitude=52.4500,
            longitude=10.5667,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=65.0,
            runways=[Runway(name="09/27", length_m=1200, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Verden-Scharnhorst",
            latitude=52.9500,
            longitude=9.2833,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=30.0,
            runways=[Runway(name="09/27", length_m=1300, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "British Army"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Walldorf",
            latitude=50.5667,
            longitude=10.7667,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=285.0,
            runways=[Runway(name="09/27", length_m=1800, width_m=40, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Waren-Vielist",
            latitude=53.5333,
            longitude=12.6833,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=65.0,
            runways=[Runway(name="09/27", length_m=1600, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Werneuchen",
            latitude=52.6333,
            longitude=13.7333,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=60.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Weser-Wümme",
            latitude=53.0833,
            longitude=9.1167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=5.0,
            runways=[Runway(name="09/27", length_m=1000, width_m=25, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Wiesbaden",
            latitude=50.0497,
            longitude=8.3253,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETOU",
            iata="WIE",
            elevation_m=138.0,
            runways=[Runway(name="08/26", length_m=3048, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "USAF"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Wiesmar",
            latitude=52.3500,
            longitude=12.8833,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=75.0,
            runways=[Runway(name="09/27", length_m=1500, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Wittstock",
            latitude=53.2083,
            longitude=12.4917,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=72.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force", "bomber"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Worms",
            latitude=49.6067,
            longitude=8.3683,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDFV",
            iata="",
            elevation_m=91.0,
            runways=[Runway(name="05/23", length_m=1400, width_m=30, heading=50.0, surface="asphalt")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["civilian", "general aviation"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Wunstorf",
            latitude=52.4572,
            longitude=9.4272,
            marker_type=MarkerType.AIRPORT.value,
            icao="ETNW",
            iata="",
            elevation_m=55.0,
            runways=[Runway(name="08/26", length_m=2440, width_m=45, heading=80.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "Luftwaffe", "transport"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Zerbst",
            latitude=51.9878,
            longitude=12.1425,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDUZ",
            iata="",
            elevation_m=86.0,
            runways=[Runway(name="09/27", length_m=2500, width_m=60, heading=90.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "airbase", "Soviet Air Force"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Zollschen",
            latitude=52.2833,
            longitude=12.6167,
            marker_type=MarkerType.AIRPORT.value,
            icao="",
            iata="",
            elevation_m=80.0,
            runways=[Runway(name="09/27", length_m=1500, width_m=30, heading=90.0, surface="grass")],
            frequencies={"tower": 120.0},
            country="East Germany",
            tags=["military", "training"],
            source="DCS World",
            map="CW Germany"
        ),
        Location(
            name="Zweibrücken",
            latitude=49.2094,
            longitude=7.4006,
            marker_type=MarkerType.AIRPORT.value,
            icao="EDRZ",
            iata="ZQW",
            elevation_m=342.0,
            runways=[Runway(name="03/21", length_m=3048, width_m=45, heading=30.0, surface="concrete")],
            frequencies={"tower": 120.0},
            country="West Germany",
            tags=["military", "airbase", "USAF", "RCAF"],
            source="DCS World",
            map="CW Germany"
        ),
    ]

    # If you add runways without `heading`, the script will try to estimate it from the name.
    for loc in samples:
        if loc.runways:
            for rw in loc.runways:
                if getattr(rw, 'heading', None) is None:
                    est = estimate_heading_from_name(rw.name)
                    if est is not None:
                        rw.heading = est

    return samples


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--replace', action='store_true', help='Delete existing location content before inserting samples')
    args = p.parse_args()

    db = MarkersDatabase()

    if args.replace:
        print('Clearing existing location-related tables (routes, locations, runways, services, media, navaids, location_tags, tags)')
        cur = db.conn.cursor()
        cur.execute("DELETE FROM route_waypoints")
        cur.execute("DELETE FROM runways")
        cur.execute("DELETE FROM services")
        cur.execute("DELETE FROM media")
        cur.execute("DELETE FROM navaids")
        cur.execute("DELETE FROM location_tags")
        cur.execute("DELETE FROM tags")
        cur.execute("DELETE FROM routes")
        cur.execute("DELETE FROM locations")
        db.conn.commit()

    samples = germany_samples()
    if not samples:
        print("No samples to insert. Add `Location` objects to `germany_samples()` and re-run the script.")
        db.close()
        return

    inserted = 0
    for loc in samples:
        try:
            new_id = db.add_location(loc)
            print(f"Inserted: {loc.name} (id={new_id})")
            inserted += 1
        except Exception as e:
            print(f"Failed inserting {loc.name}: {e}")

    print(f"\nInserted {inserted} sample locations")
    print(f"Total locations now: {len(db.get_all_locations())}")
    db.close()


if __name__ == '__main__':
    main()
