#!/usr/bin/env python3
"""
forward_parsed_udp.py
Tail a JSON-lines file (player_aircraft_parsed.jsonl) and send each JSON object
as a single UDP datagram to a configured host:port.

Now with AES-GCM encryption for secure data transmission!

Usage examples:
  python forward_parsed_udp.py --host 192.168.178.100 --port 5010
  python forward_parsed_udp.py --once --send-existing

Requires: pip install cryptography

This script is safe to run outside DCS and avoids modifying any DCS files.
"""

from __future__ import annotations
import argparse
import os
import socket
import sys
import time
import json
import logging
import traceback
import re
import glob
from datetime import datetime
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.backends import default_backend

# Setup logger
logger = logging.getLogger(__name__)

# Import SessionManager for ECDH handshake
try:
    from crypto_handshake import SessionManager
    HANDSHAKE_AVAILABLE = True
except ImportError:
    HANDSHAKE_AVAILABLE = False
    sys.stderr.write("⚠️ Warning: crypto_handshake.py not found, ECDH mode unavailable\n")

DEFAULT_FILE = os.path.expanduser(r"~\Saved Games\DCS\Scripts\player_aircraft_parsed.jsonl")
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5010

# PSK mode removed - ECDH only


def find_dcs_scripts_folder() -> str | None:
    """Attempt to locate the user's DCS "Saved Games/.../DCS/Scripts" folder.

    Returns absolute path to Scripts folder or None if not found.
    """
    try:
        # Typical Windows location under user's profile
        home = os.path.expanduser("~")
        candidate = os.path.join(home, "Saved Games", "DCS", "Scripts")
        if os.path.isdir(candidate):
            return candidate

        # Look for directories under "Saved Games" that start with 'DCS'
        saved_games = os.path.join(home, "Saved Games")
        if os.path.isdir(saved_games):
            for entry in os.listdir(saved_games):
                if entry.lower().startswith('dcs'):
                    p = os.path.join(saved_games, entry, "Scripts")
                    if os.path.isdir(p):
                        return p

        # Fallback: search current working directory tree for a 'Scripts' folder that contains export.lua
        cwd = os.getcwd()
        for root, dirs, files in os.walk(cwd):
            if 'Scripts' in dirs:
                scripts_dir = os.path.join(root, 'Scripts')
                if os.path.exists(os.path.join(scripts_dir, 'export.lua')):
                    return scripts_dir
    except Exception:
        pass
    return None


def find_export_file(scripts_dir: str) -> str | None:
    """Find the most recent export JSON/JSONL file generated by export.lua or similar.

    Looks for common filenames and returns the newest match or None.
    """
    if not scripts_dir or not os.path.isdir(scripts_dir):
        return None

    patterns = [
        'player_aircraft_parsed.jsonl',
        'export.json',
        'export.jsonl',
        'export_*.json',
        'export_*.jsonl',
        'player_*.json',
        'player_*.jsonl',
        '*.export.json',
        '*.export.jsonl'
    ]

    matches = []
    for pat in patterns:
        globpat = os.path.join(scripts_dir, pat)
        for p in glob.glob(globpat):
            if os.path.isfile(p):
                matches.append(p)

    if not matches:
        # Recursively search one level deeper just in case
        for sub in os.listdir(scripts_dir):
            subp = os.path.join(scripts_dir, sub)
            if os.path.isdir(subp):
                for pat in patterns:
                    globpat = os.path.join(subp, pat)
                    for p in glob.glob(globpat):
                        if os.path.isfile(p):
                            matches.append(p)

    if not matches:
        return None

    # Return the most recently modified match
    matches.sort(key=lambda p: os.path.getmtime(p), reverse=True)
    return matches[0]


def check_bind_security(bind_ip: str):
    """Enhanced bind security check.

    - Disallow 0.0.0.0 unconditionally.
    - Warn (and require confirmation) for public IPs.
    - Recommend using 127.0.0.1 for maximum safety.
    """
    if bind_ip == '0.0.0.0':
        sys.stderr.write("\n" + "="*70 + "\n")
        sys.stderr.write("🚨 CRITICAL SECURITY WARNING: Binding to ALL network interfaces is BLOCKED!\n")
        sys.stderr.write("="*70 + "\n")
        sys.stderr.write("This exposes your server to:\n")
        sys.stderr.write("  - Internet (if PC has public IP)\n")
        sys.stderr.write("  - Local network (LAN)\n")
        sys.stderr.write("  - VPN connections\n")
        sys.stderr.write("  - ALL other network interfaces\n")
        sys.stderr.write("\n")
        sys.stderr.write("BINDING TO 0.0.0.0 IS NOT ALLOWED.\n")
        sys.stderr.write("Use --bind-ip 127.0.0.1 (localhost only) or a specific LAN IP.\n")
        sys.stderr.write("="*70 + "\n")
        sys.stderr.write("\n❌ Aborted. Binding to 0.0.0.0 is forbidden for security reasons.\n")
        sys.exit(1)

    # Try to determine if the provided bind_ip is a public IP address.
    try:
        import ipaddress
        addr = ipaddress.ip_address(bind_ip)
        if not (addr.is_private or addr.is_loopback):
            sys.stderr.write("\n" + "="*70 + "\n")
            sys.stderr.write(f"⚠️ WARNING: Binding to public IP {bind_ip}!\n")
            sys.stderr.write("This may expose the handshake listener to the internet or other untrusted networks.\n")
            sys.stderr.write("If you really intend to bind to this IP, type 'ACCEPT_PUBLIC' to continue.\n")
            sys.stderr.write("="*70 + "\n")
            try:
                response = input("Type 'ACCEPT_PUBLIC' to continue: ")
            except (EOFError, KeyboardInterrupt):
                response = ''
            if response.strip() != 'ACCEPT_PUBLIC':
                sys.stderr.write("\n❌ Aborted. Binding to public IP not confirmed.\n")
                sys.exit(1)
    except Exception:
        # Could not parse IP (e.g. hostname) — warn and proceed, but log warning
        logger.warning(f"⚠️ Could not determine if bind IP {bind_ip} is public; ensure this is intended")

    # Recommend localhost for maximum safety
    if bind_ip != '127.0.0.1':
        logger.warning(f"⚠️ Binding to {bind_ip} - consider using 127.0.0.1 for localhost only")

# DoS protection: Global message rate limiting
_message_timestamps = []  # List of timestamps for received messages
_rate_limit_lock = __import__('threading').Lock()
_MAX_MESSAGES_PER_SECOND = 50  # Reduced from 100 to 50 for better DoS protection
_RATE_LIMIT_WINDOW_SECONDS = 1.0  # 1 second window

# DoS protection: Per-IP rate limiting (independent of SessionManager)
_ip_rate_limits = {}  # IP -> (message_count, window_start_time, violation_count)
_MAX_MESSAGES_PER_IP = 5  # Maximum 5 messages per IP per window (strict)
_IP_RATE_LIMIT_WINDOW = 10.0  # 10 second window
_IP_BAN_DURATION = 300.0  # 5 minutes ban for violators
_ip_bans = {}  # IP -> ban_until_timestamp

# DoS protection: Message size limits
_MAX_HANDSHAKE_MESSAGE_SIZE = 8192  # 8KB max for handshake messages (prevents large payload attacks)

# Maximum UDP payload (protocol limit). Subtract AEAD overhead when encrypting
# to ensure ciphertext fits into a single UDP datagram.
_UDP_MAX_PAYLOAD = 65507
_AES_GCM_OVERHEAD = 12 + 16  # nonce + tag
# Conservative plaintext maximum so encrypted packet stays under UDP limit
_MAX_DATA_MESSAGE_SIZE = _UDP_MAX_PAYLOAD - _AES_GCM_OVERHEAD


def validate_data_message(data: bytes, encrypt: bool = True) -> bool:
    """Validate data message size before sending.

    Returns: True if the data is within allowed limits, False otherwise.
    """
    if encrypt:
        allowed = _MAX_DATA_MESSAGE_SIZE
    else:
        allowed = _UDP_MAX_PAYLOAD

    if len(data) > allowed:
        logger.warning(f"⚠️ Oversized data message: {len(data)} bytes (max {allowed})")
        return False
    return True


def find_device_for_session(session_mgr: 'SessionManager', session_id: str) -> str | None:
    """Return the device_id associated with the given session_id, or None if not found.

    This helper performs a safe lookup in SessionManager.device_sessions.
    """
    try:
        for device_id, sid in session_mgr.device_sessions.items():
            if sid == session_id:
                return device_id
    except Exception:
        # Defensive: if device_sessions isn't available or not a mapping
        pass
    return None


# Timestamp filtering to prevent forwarding of old/cached data
# Stores last processed timestamp as ISO-8601 string (or None)
_last_processed_timestamp = None

def _parse_iso_timestamp(ts_str: str):
    try:
        if not isinstance(ts_str, str):
            return None
        # Accept trailing 'Z' as UTC
        if ts_str.endswith('Z'):
            ts_str = ts_str[:-1] + '+00:00'
        return datetime.fromisoformat(ts_str)
    except Exception:
        return None


def _timestamp_is_newer(current_ts: str, last_ts: str) -> bool:
    # Treat missing timestamps as newer (accept)
    if current_ts is None:
        return True
    if last_ts is None:
        return True

    cur = _parse_iso_timestamp(current_ts)
    last = _parse_iso_timestamp(last_ts)
    if cur is not None and last is not None:
        return cur > last

    # Fallback to lexicographic comparison for identical ISO-8601 formats
    try:
        return current_ts > last_ts
    except Exception:
        return True


def check_ip_banned(ip: str) -> bool:
    """Check if IP is currently banned.

    Returns True if banned, False otherwise.
    """
    with _rate_limit_lock:
        if ip in _ip_bans:
            ban_until = _ip_bans[ip]
            if time.time() < ban_until:
                return True
            else:
                # Ban expired, remove
                del _ip_bans[ip]
        return False

def ban_ip(ip: str):
    """Ban an IP address temporarily."""
    with _rate_limit_lock:
        ban_until = time.time() + _IP_BAN_DURATION
        _ip_bans[ip] = ban_until
        logger.warning(f"🚫 Banned IP {ip} for {_IP_BAN_DURATION/60:.1f} minutes due to rate limit violations")

def check_ip_rate_limit(ip: str) -> bool:
    """Check per-IP rate limit (strict, independent of SessionManager).

    Returns True if rate limit is OK, False if exceeded.
    """
    with _rate_limit_lock:
        current_time = time.time()

        if ip in _ip_rate_limits:
            count, window_start, violations = _ip_rate_limits[ip]

            # Check if window expired
            if current_time - window_start > _IP_RATE_LIMIT_WINDOW:
                # Reset window
                _ip_rate_limits[ip] = (1, current_time, violations)
                return True

            # Within window - check count
            if count >= _MAX_MESSAGES_PER_IP:
                logger.warning(f"⚠️ IP rate limit exceeded for {ip}: {count} messages in {current_time - window_start:.1f}s")
                # Increment violations and ban
                _ip_rate_limits[ip] = (count, window_start, violations + 1)
                ban_ip(ip)
                return False

            # Increment count
            _ip_rate_limits[ip] = (count + 1, window_start, violations)
            return True
        else:
            # First message from this IP
            _ip_rate_limits[ip] = (1, current_time, 0)
            return True

def cleanup_rate_limits():
    """Cleanup expired rate limit entries to prevent memory leak."""
    with _rate_limit_lock:
        current_time = time.time()

        # Cleanup IP rate limits (keep for 2x window after last activity)
        expired_ips = [
            ip for ip, (_, window_start, _) in _ip_rate_limits.items()
            if current_time - window_start > _IP_RATE_LIMIT_WINDOW * 2
        ]
        for ip in expired_ips:
            del _ip_rate_limits[ip]

        # Cleanup expired bans
        expired_bans = [
            ip for ip, ban_until in _ip_bans.items()
            if current_time > ban_until + 3600  # Keep for 1 hour after expiry for logging
        ]
        for ip in expired_bans:
            del _ip_bans[ip]

def check_global_rate_limit() -> bool:
    """Check if global message rate limit is exceeded (DoS protection).

    Returns True if rate limit is OK, False if exceeded.
    """
    global _message_timestamps
    with _rate_limit_lock:
        current_time = time.time()

        # Remove timestamps older than the window
        cutoff_time = current_time - _RATE_LIMIT_WINDOW_SECONDS
        _message_timestamps = [ts for ts in _message_timestamps if ts > cutoff_time]

        # Check if we're over the limit
        if len(_message_timestamps) >= _MAX_MESSAGES_PER_SECOND:
            logger.warning(f"⚠️ Global message rate limit exceeded: {len(_message_timestamps)} messages in last {_RATE_LIMIT_WINDOW_SECONDS}s")
            return False

        # Record this message
        _message_timestamps.append(current_time)
        return True

def validate_handshake_message(data: bytes, addr: tuple) -> bool:
    """Early validation of handshake message before expensive parsing.

    This provides DoS protection by rejecting invalid messages early.

    Returns True if message passes validation, False otherwise.
    """
    ip = addr[0]

    # 1. Check IP ban status first (cheapest check)
    if check_ip_banned(ip):
        logger.debug(f"🚫 Rejected message from banned IP {ip}")
        return False

    # 2. Check message size (prevent large payload attacks)
    if len(data) > _MAX_HANDSHAKE_MESSAGE_SIZE:
        logger.warning(f"⚠️ Oversized handshake message from {ip}: {len(data)} bytes (max {_MAX_HANDSHAKE_MESSAGE_SIZE})")
        ban_ip(ip)
        return False

    if len(data) < 10:  # Minimum reasonable JSON size
        logger.debug(f"⚠️ Undersized message from {ip}: {len(data)} bytes")
        return False

    # 3. Check per-IP rate limit (before global to catch targeted attacks)
    if not check_ip_rate_limit(ip):
        return False

    # 4. Check global rate limit (prevent distributed floods)
    if not check_global_rate_limit():
        logger.warning(f"🚫 Dropping message from {ip} due to global rate limit")
        return False

    # 5. Basic format validation (check for JSON-like structure without full parsing)
    try:
        # Quick check: message should start with '{' and end with '}'
        data_str = data.decode('utf-8', errors='strict')
        stripped = data_str.strip()
        if not (stripped.startswith('{') and stripped.endswith('}')):
            logger.debug(f"⚠️ Invalid JSON format from {ip}")
            return False
    except UnicodeDecodeError:
        logger.warning(f"⚠️ Invalid UTF-8 from {ip}")
        return False

    return True


# Safe JSON parsing helper to limit size and nesting depth
def safe_json_parse(data: bytes | str, max_size: int = 8192, max_depth: int = 6) -> dict | None:
    """Safely parse JSON with size and depth limits.

    SECURITY: Size check happens BEFORE any parsing to prevent DoS attacks.
    Uses custom decoder with depth tracking to avoid JSON bombs.

    Returns a dict/list on success or None on failure.
    """
    try:
        # SECURITY: Check size BEFORE any processing (prevents memory exhaustion)
        if isinstance(data, bytes):
            if len(data) > max_size:
                logger.warning(f"⚠️ JSON too large: {len(data)} > {max_size} bytes")
                return None
            json_str = data.decode('utf-8', errors='strict')
        else:
            json_str = str(data)
            # Check encoded size
            encoded_size = len(json_str.encode('utf-8'))
            if encoded_size > max_size:
                logger.warning(f"⚠️ JSON too large: {encoded_size} > {max_size} bytes")
                return None

        # Custom JSON decoder with depth tracking (prevents CPU exhaustion from deep nesting)
        class DepthTrackingDecoder(json.JSONDecoder):
            def __init__(self, max_depth, *args, **kwargs):
                self.max_depth = max_depth
                super().__init__(*args, **kwargs)

            def decode(self, s, **kwargs):
                return self._decode_with_depth(s, 0)

            def _decode_with_depth(self, s, depth):
                if depth > self.max_depth:
                    raise ValueError(f"JSON nesting depth exceeds limit of {self.max_depth}")
                # Use the parent decoder but intercept object_hook to track depth
                original_object_hook = self.object_hook
                def depth_checking_hook(obj):
                    if depth + 1 > self.max_depth:
                        raise ValueError(f"JSON nesting depth exceeds limit of {self.max_depth}")
                    return original_object_hook(obj) if original_object_hook else obj

                self.object_hook = depth_checking_hook
                try:
                    result = super(DepthTrackingDecoder, self).decode(s)
                    return result
                finally:
                    self.object_hook = original_object_hook

        # Parse with depth-limited decoder
        decoder = DepthTrackingDecoder(max_depth)
        obj = decoder.decode(json_str)

        # Additional validation: ensure result is a dict or list (expected structures)
        if not isinstance(obj, (dict, list)):
            logger.warning("⚠️ JSON root must be object or array")
            return None

        return obj
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError, RecursionError) as e:
        logger.warning(f"⚠️ Invalid or unsafe JSON: {e}")
        return None

def send_udp(payload: bytes, host: str, port: int, sock: socket.socket,
             session_mgr: 'SessionManager', device_id: str) -> bool:
    """Send UDP packet with ECDH encryption

    Args:
        payload: Data to send
        host: Destination host
        port: Destination port
        sock: UDP socket
        session_mgr: SessionManager instance (required for ECDH mode)
        device_id: Device ID to send to (looks up active session)
    """
    try:
        # Validate payload size before doing expensive encryption work
        if not validate_data_message(payload, encrypt=True):
            return False

        # Get session for device and encrypt with session key
        session_id = session_mgr.device_sessions.get(device_id)
        if not session_id:
            # No active session for this device
            return False

        encrypted = session_mgr.encrypt_with_session(payload, session_id)
        if not encrypted:
            # Session expired or encryption failed
            return False

        sock.sendto(encrypted, (host, port))
        return True
    except Exception as e:
        print(f"Send error: {e}", file=sys.stderr)
        return False


def extract_json_from_line(line: str) -> str | None:
    # find JSON object start and end (first '{' and last '}') and extract that range
    idx = line.find('{')
    if idx == -1:
        # No JSON object start found: do not attempt to send arbitrary non-JSON lines
        return None

    end_idx = line.rfind('}')
    if end_idx == -1 or end_idx <= idx:
        # No JSON object end found or malformed
        return None

    # Return the substring that should represent a JSON object
    s = line[idx:end_idx + 1].strip()
    return s if s else None


def _is_same_file(f, path: str) -> bool:
    """Return True if file object ``f`` refers to the same underlying file as ``path``.

    Uses inode/device when available; on platforms where inode isn't meaningful,
    falls back to modification time and size.
    """
    try:
        st1 = os.fstat(f.fileno())
        st2 = os.stat(path)
    except Exception:
        return False

    # prefer device/inode when present
    if hasattr(st1, 'st_ino') and hasattr(st2, 'st_ino') and st1.st_ino and st2.st_ino:
        return (st1.st_ino == st2.st_ino) and (getattr(st1, 'st_dev', None) == getattr(st2, 'st_dev', None))

    # fallback to mtime+size comparison
    return (int(st1.st_mtime) == int(st2.st_mtime)) and (st1.st_size == st2.st_size)


def tail_and_send(path: str, host: str, port: int, session_mgr: 'SessionManager', send_existing=False, once=False, interval=0.2,
                  verbose=False, show_env=False, handshake_port: int = None, bind_ip: str = '127.0.0.1'):
    """Tail a file and send only new JSON lines as UDP datagrams (ECDH only)."""
    # Use global timestamp state to prevent forwarding old/cached messages
    global _last_processed_timestamp
    if not os.path.exists(path):
        raise FileNotFoundError(path)

    # Create a UDP socket bound to handshake_port for handshake, send data to destination port
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    # SECURITY: Default bind to localhost only for safety
    # Use handshake_port if specified, otherwise use data port
    listen_port = handshake_port if handshake_port is not None else port
    sock.bind((bind_ip, listen_port))  # Bind to specified IP (default: localhost)
    # Use configured interval for socket timeout (non-blocking with fast response)
    sock.settimeout(max(0.01, interval))  # At least 10ms, use configured interval
    logger.info(f"🔐 Listening for handshakes on {bind_ip}:{listen_port}")
    if handshake_port is not None and handshake_port != port:
        logger.info(f"📤 Will send data to {host}:{port}")
    handshake_sock = sock  # Use same socket for handshake and data

    # Heartbeat tracking: send heartbeat every 30 seconds when no new data
    last_data_sent_time = time.time()
    HEARTBEAT_INTERVAL = 30.0  # seconds

    def open_for_tail(read_existing: bool = False):
        f = open(path, 'r', encoding='utf-8', errors='ignore')
        if not read_existing:
            f.seek(0, os.SEEK_END)
        return f

    f = open_for_tail()
    try:
        while True:
            # Check heartbeat FIRST (independent of data availability)
            current_time = time.time()
            if current_time - last_data_sent_time >= HEARTBEAT_INTERVAL:
                heartbeat_data = {
                    "type": "heartbeat",
                    "timestamp": datetime.now().isoformat() + 'Z',
                    "message": "No new flight data - connection alive"
                }
                heartbeat_json = json.dumps(heartbeat_data).encode('utf-8')
                
                # Send heartbeat to all active sessions
                heartbeat_sent = False
                for device_id in list(session_mgr.device_sessions.keys()):
                    if send_udp(heartbeat_json, host, port, sock,
                               session_mgr=session_mgr, device_id=device_id):
                        logger.info(f"💓 Heartbeat sent to {device_id[:8]}...")
                        heartbeat_sent = True
                
                if heartbeat_sent:
                    last_data_sent_time = current_time

            # In ECDH mode: check for incoming handshake messages
            if handshake_sock:
                try:
                    data, addr = handshake_sock.recvfrom(65535)  # Max UDP size

                    # SECURITY: Early validation before expensive parsing (DoS protection)
                    if not validate_handshake_message(data, addr):
                        # Message rejected by validation (rate limit, size, format, etc.)
                        continue

                    # Try to parse as handshake message (PLAINTEXT - no PSK encryption)
                    try:
                        # Use safe parser with size and depth limits
                        msg = safe_json_parse(data, max_size=_MAX_HANDSHAKE_MESSAGE_SIZE)
                        if not msg:
                            # Parsing failed or message too large
                            continue

                        if 'type' in msg and msg['type'] == 'ClientHello':
                            logger.info(f"📥 Received ClientHello from {addr}")
                            response = session_mgr.handle_client_hello(msg, addr)
                            # Send response in PLAINTEXT (no PSK encryption)
                            response_json = json.dumps(response).encode('utf-8')
                            handshake_sock.sendto(response_json, addr)
                            logger.info(f"📤 Sent ServerHello to {addr}")
                        elif 'type' in msg and msg['type'] == 'KeyConfirm':
                            logger.info(f"📥 Received KeyConfirm from {addr}")
                            response = session_mgr.handle_key_confirm(msg)
                            # Send response in PLAINTEXT (no PSK encryption)
                            response_json = json.dumps(response).encode('utf-8')
                            handshake_sock.sendto(response_json, addr)
                            if response.get('status') == 'ready':
                                logger.info(f"✅ Session established with device {msg.get('sessionId', 'unknown')[:8]}...")

                                # Send one immediate heartbeat to the newly established device so it has
                                # a fresh timestamp and avoids rejected/old-data behavior.
                                session_id = msg.get('sessionId')
                                device_id = find_device_for_session(session_mgr, session_id) if session_id else None
                                if device_id:
                                    heartbeat_data = {
                                        "type": "heartbeat",
                                        "timestamp": datetime.now().isoformat() + 'Z',
                                        "message": "Initial heartbeat after handshake"
                                    }
                                    heartbeat_json = json.dumps(heartbeat_data).encode('utf-8')
                                    try:
                                        if send_udp(heartbeat_json, host, port, handshake_sock,
                                                    session_mgr=session_mgr, device_id=device_id):
                                            logger.info(f"💓 Initial heartbeat sent to {device_id[:8]}...")
                                            # Update last_data_sent_time so we don't immediately send another heartbeat
                                            try:
                                                last_data_sent_time = time.time()
                                            except Exception:
                                                pass
                                        else:
                                            logger.warning(f"⚠️ Failed to send initial heartbeat to {device_id[:8]} (session may have expired)")
                                    except Exception as e:
                                        logger.warning(f"⚠️ Error sending initial heartbeat: {e}")
                    except Exception as decode_err:
                        # Not a handshake message or malformed, ignore
                        logger.debug(f"Failed to parse handshake: {decode_err}")
                        pass
                except socket.timeout:
                    # No handshake message, continue
                    pass
                except Exception as e:
                    logger.debug(f"Handshake check error: {e}")
            
            line = f.readline()
            if not line:
                try:
                    cur_pos = f.tell()
                    size = os.path.getsize(path)
                except OSError:
                    try:
                        f.close()
                    except Exception:
                        pass
                    f = open_for_tail(True)
                    if once:
                        break
                    time.sleep(interval)
                    continue

                if cur_pos > size:
                    try:
                        f.close()
                    except Exception:
                        pass
                    f = open_for_tail(True)
                    if once:
                        break
                    time.sleep(interval)
                    continue

                if not _is_same_file(f, path):
                    try:
                        f.close()
                    except Exception:
                        pass
                    f = open_for_tail(True)
                    if once:
                        break
                    time.sleep(interval)
                    continue

                if once:
                    break
                time.sleep(interval)
                continue

            jsonpart = extract_json_from_line(line)
            if not jsonpart:
                continue

            # Validate that the extracted substring is valid JSON before sending
            parsed = safe_json_parse(jsonpart, max_size=_MAX_DATA_MESSAGE_SIZE)
            if parsed is None:
                logger.debug("Skipping invalid/empty JSON line")
                continue

            # Timestamp validation: reject old/cached messages (prevents client position resets)
            try:
                cur_ts = parsed.get('timestamp')
            except Exception:
                cur_ts = None

            if not _timestamp_is_newer(cur_ts, _last_processed_timestamp):
                logger.warning(f"⚠️ REJECTED OLD DATA: timestamp={cur_ts} (last={_last_processed_timestamp}) - preventing position reset!")
                continue

            # Accept and record timestamp
            if cur_ts is not None:
                logger.info(f"✅ Accepted data with timestamp={cur_ts}")
                _last_processed_timestamp = cur_ts

            # Send to all devices with active sessions (ECDH mode)
            sent_count = 0
            for device_id, session_id in list(session_mgr.device_sessions.items()):
                # Get device info for logging
                device = session_mgr.authorized_devices.get(device_id)
                device_name = device.name if device else device_id[:8]

                if send_udp(jsonpart.encode('utf-8'), host, port, sock,
                           session_mgr=session_mgr, device_id=device_id):
                    sent_count += 1
                else:
                    logger.warning(f"⚠️ Failed to send to {device_name} (session may have expired)")

            sent = sent_count > 0
            
            # Update last data sent time on successful send
            if sent:
                last_data_sent_time = time.time()
            
            if verbose or show_env:
                ts = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
                if sent:
                    if show_env:
                        try:
                            parsed = safe_json_parse(jsonpart, max_size=_MAX_DATA_MESSAGE_SIZE)
                            if parsed is not None:
                                env = parsed.get('environment', {})
                                temp = parsed.get('temperature', env.get('temperature'))
                                pres = parsed.get('pressure', env.get('pressure'))
                                wind = env.get('wind') or {'speed': env.get('windSpeed'), 'direction': env.get('windDirection')}
                                wspeed = wind.get('speed')
                                wdir = wind.get('direction')
                                print(f"{ts} SENT {host}:{port} temp={temp}C pres={pres} wind={wspeed}@{wdir}")
                            else:
                                print(f"{ts} SENT {host}:{port} {jsonpart}")
                        except Exception:
                            print(f"{ts} SENT {host}:{port} {jsonpart}")
                    else:
                        print(f"{ts} SENT {host}:{port} {jsonpart}")
                else:
                    print(f"{ts} ERROR {host}:{port} {jsonpart}")
    finally:
        try:
            f.close()
        except Exception:
            pass
        sock.close()
        # handshake_sock is same as sock in ECDH mode, don't close twice


def get_last_line(path: str) -> str | None:
    """Efficiently read the last complete line from a file by seeking from the end.
    
    This avoids reading the entire file, which is important for large JSONL files.
    Returns None if file is empty or only contains incomplete lines.
    
    Note: Opens file fresh each time to avoid stale cache issues.
    """
    try:
        with open(path, 'rb') as f:
            # Seek to end
            f.seek(0, os.SEEK_END)
            file_size = f.tell()
            
            if file_size == 0:
                return None
            
            # Read backwards in chunks to find last complete line
            # We read up to 64KB from the end, which should be enough for any JSON line
            chunk_size = min(65536, file_size)
            f.seek(-chunk_size, os.SEEK_END)
            
            # Read chunk and decode
            chunk = f.read(chunk_size)
            try:
                text = chunk.decode('utf-8', errors='ignore')
            except Exception:
                return None
            
            # Find last complete line (split by newline and take last non-empty)
            lines = text.split('\n')
            # Work backwards to find last non-empty line
            for i in range(len(lines) - 1, -1, -1):
                line = lines[i].strip()
                if line:
                    return line
            
            return None
    except Exception as e:
        logger.debug(f"Error reading last line: {e}")
        return None


# New feature: repeat the last line every X seconds
def repeat_last_line(path: str, host: str, port: int, session_mgr: 'SessionManager', interval=5.0, verbose=False, show_env=False,
                     handshake_port: int = None, bind_ip: str = '127.0.0.1'):
    """Send the last line of the file as a UDP datagram every <interval> seconds (ECDH only)."""
    # Use global timestamp state to prevent forwarding old/cached messages
    global _last_processed_timestamp
    if not os.path.exists(path):
        raise FileNotFoundError(path)

    # Create a UDP socket bound to handshake_port for handshake, send data to destination port
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    # SECURITY: Default bind to localhost only for safety
    # Use handshake_port if specified, otherwise use data port
    listen_port = handshake_port if handshake_port is not None else port
    sock.bind((bind_ip, listen_port))  # Bind to specified IP (default: localhost)
    # Use configured interval for socket timeout (non-blocking with fast response)
    sock.settimeout(max(0.01, interval))  # At least 10ms, use configured interval
    logger.info(f"🔐 Listening for handshakes on {bind_ip}:{listen_port}")
    if handshake_port is not None and handshake_port != port:
        logger.info(f"📤 Will send data to {host}:{port}")
    handshake_sock = sock  # Use same socket for handshake and data
    
    # Heartbeat tracking: send heartbeat every 30 seconds when no new data
    last_data_sent_time = time.time()
    HEARTBEAT_INTERVAL = 30.0  # seconds
    
    try:
        last_sent = None
        last_send_time = 0
        last_file_mtime = 0  # Track file modification time to detect changes
        cached_last_line = None  # Cache the last line to avoid unnecessary reads
        
        while True:
            # Check heartbeat FIRST (independent of data availability)
            current_time = time.time()
            if current_time - last_data_sent_time >= HEARTBEAT_INTERVAL:
                heartbeat_data = {
                    "type": "heartbeat",
                    "timestamp": datetime.now().isoformat() + 'Z',
                    "message": "No new flight data - connection alive"
                }
                heartbeat_json = json.dumps(heartbeat_data).encode('utf-8')
                
                # Send heartbeat to all active sessions
                heartbeat_sent = False
                for device_id in list(session_mgr.device_sessions.keys()):
                    if send_udp(heartbeat_json, host, port, sock,
                               session_mgr=session_mgr, device_id=device_id):
                        logger.info(f"💓 Heartbeat sent to {device_id[:8]}...")
                        heartbeat_sent = True
                
                if heartbeat_sent:
                    last_data_sent_time = current_time

            # In ECDH mode: check for incoming handshake messages
            if handshake_sock:
                try:
                    data, addr = handshake_sock.recvfrom(65535)  # Max UDP size

                    # SECURITY: Early validation before expensive parsing (DoS protection)
                    if not validate_handshake_message(data, addr):
                        # Message rejected by validation (rate limit, size, format, etc.)
                        continue

                    # Parse handshake message (PLAINTEXT - no PSK encryption)
                    try:
                        logger.debug(f"📦 Received {len(data)} bytes from {addr}")

                        # Handshake messages are sent in PLAINTEXT for proper ECDH
                        msg = safe_json_parse(data, max_size=_MAX_HANDSHAKE_MESSAGE_SIZE)
                        if not msg:
                            logger.debug("Failed to parse handshake message or message too large")
                            continue

                        # SECURITY: Avoid logging full message contents; show a short preview/truncated
                        try:
                            preview = json.dumps(msg)
                            logger.debug(f"📄 Full message (truncated): {preview[:200]}")
                        except Exception:
                            logger.debug("📄 Full message: <unserializable>")

                        logger.info(f"📨 Received {msg.get('type', 'Unknown')} from {addr[0]}")
                        logger.debug(f"📊 Message keys: {list(msg.keys())}")

                        if 'type' in msg and msg['type'] == 'ClientHello':
                            logger.info(f"📥 Received ClientHello from {addr}")
                            response = session_mgr.handle_client_hello(msg, addr)
                            # Send response in PLAINTEXT (no PSK encryption)
                            response_json = json.dumps(response).encode('utf-8')
                            handshake_sock.sendto(response_json, addr)
                            logger.info(f"📤 Sent ServerHello to {addr}")
                        elif 'type' in msg and msg['type'] == 'KeyConfirm':
                            logger.info(f"📥 Received KeyConfirm from {addr}")
                            response = session_mgr.handle_key_confirm(msg)
                            # Send response in PLAINTEXT (no PSK encryption)
                            response_json = json.dumps(response).encode('utf-8')
                            handshake_sock.sendto(response_json, addr)
                            if response.get('status') == 'ready':
                                logger.info(f"✅ Session established with device {msg.get('sessionId', 'unknown')[:8]}...")

                                # Send one immediate heartbeat to the newly established device so it has
                                # a fresh timestamp and avoids rejected/old-data behavior.
                                session_id = msg.get('sessionId')
                                device_id = find_device_for_session(session_mgr, session_id) if session_id else None
                                if device_id:
                                    heartbeat_data = {
                                        "type": "heartbeat",
                                        "timestamp": datetime.now().isoformat() + 'Z',
                                        "message": "Initial heartbeat after handshake"
                                    }
                                    heartbeat_json = json.dumps(heartbeat_data).encode('utf-8')
                                    try:
                                        if send_udp(heartbeat_json, host, port, handshake_sock,
                                                    session_mgr=session_mgr, device_id=device_id):
                                            logger.info(f"💓 Initial heartbeat sent to {device_id[:8]}...")
                                            # Update last_data_sent_time so we don't immediately send another heartbeat
                                            try:
                                                last_data_sent_time = time.time()
                                            except Exception:
                                                pass
                                        else:
                                            logger.warning(f"⚠️ Failed to send initial heartbeat to {device_id[:8]} (session may have expired)")
                                    except Exception as e:
                                        logger.warning(f"⚠️ Error sending initial heartbeat: {e}")
                    except Exception as decode_err:
                        # Not a handshake message or malformed, ignore
                        logger.debug(f"Failed to parse handshake: {decode_err}")
                        pass
                    except Exception as unexpected_err:
                        # Log unexpected errors for debugging
                        logger.warning(f"⚠️ Unexpected error parsing handshake: {unexpected_err}")
                except socket.timeout:
                    # No handshake message, continue
                    pass
                except Exception as e:
                    logger.debug(f"Handshake check error: {e}")
            
            # Send data at regular interval
            current_time = time.time()
            if current_time - last_send_time < interval:
                # Don't sleep - socket timeout handles the wait
                continue
            
            try:
                # Check if file has been modified since last read
                try:
                    file_mtime = os.path.getmtime(path)
                except OSError:
                    continue
                
                # Only read file if it has been modified OR we haven't cached anything yet
                if file_mtime != last_file_mtime or cached_last_line is None:
                    last_line = get_last_line(path)
                    if last_line:
                        cached_last_line = last_line
                        last_file_mtime = file_mtime
                        logger.debug(f"📄 Updated cached line from file (mtime: {file_mtime})")
                    else:
                        continue
                else:
                    # Use cached line (file hasn't changed)
                    last_line = cached_last_line
                    logger.debug("📦 Using cached last line (file unchanged)")
                
                if not last_line:
                    continue
                    
                jsonpart = extract_json_from_line(last_line)
                if not jsonpart:
                    continue

                # Validate that the extracted substring is valid JSON before sending
                parsed = safe_json_parse(jsonpart, max_size=_MAX_DATA_MESSAGE_SIZE)
                if parsed is None:
                    continue

                # Timestamp validation: reject old/cached messages
                try:
                    cur_ts = parsed.get('timestamp')
                except Exception:
                    cur_ts = None

                if not _timestamp_is_newer(cur_ts, _last_processed_timestamp):
                    logger.warning(f"⚠️ REJECTED OLD DATA: timestamp={cur_ts} (last={_last_processed_timestamp}) - preventing position reset!")
                    continue

                # Accept and record timestamp
                if cur_ts is not None:
                    logger.info(f"✅ Accepted data with timestamp={cur_ts}")
                    _last_processed_timestamp = cur_ts

                # Send to all devices with active sessions (ECDH mode)
                sent_count = 0
                for device_id, session_id in list(session_mgr.device_sessions.items()):
                    # Get device info for logging
                    device = session_mgr.authorized_devices.get(device_id)
                    device_name = device.name if device else device_id[:8]

                    if send_udp(jsonpart.encode('utf-8'), host, port, sock,
                               session_mgr=session_mgr, device_id=device_id):
                        sent_count += 1
                    else:
                        logger.warning(f"⚠️ Failed to send to {device_name} (session may have expired)")
                sent = sent_count > 0
                
                # Update last data sent time on successful send
                if sent:
                    last_data_sent_time = current_time
                
                last_send_time = current_time
                if verbose or show_env:
                    ts = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
                    if sent:
                        if show_env:
                            try:
                                parsed = safe_json_parse(jsonpart, max_size=_MAX_DATA_MESSAGE_SIZE)
                                if parsed is not None:
                                    env = parsed.get('environment', {})
                                    temp = parsed.get('temperature', env.get('temperature'))
                                    pres = parsed.get('pressure', env.get('pressure'))
                                    wind = parsed.get('wind') or {'speed': env.get('windSpeed'), 'direction': env.get('windDirection')}
                                    wspeed = wind.get('speed')
                                    wdir = wind.get('direction')
                                    print(f"{ts} REPEAT {host}:{port} temp={temp}C pres={pres} wind={wspeed}@{wdir}")
                                else:
                                    print(f"{ts} REPEAT {host}:{port} {jsonpart}")
                            except Exception:
                                print(f"{ts} REPEAT {host}:{port} {jsonpart}")
                        else:
                            print(f"{ts} REPEAT {host}:{port} {jsonpart}")
                    else:
                        print(f"{ts} ERROR {host}:{port} {jsonpart}")
            except Exception as e:
                print(f"Error reading/sending: {e}", file=sys.stderr)
    finally:
        sock.close()
        # handshake_sock is same as sock in ECDH mode, don't close twice


def write_live_command(interval_ms: int, scripts_dir: str = None):
    """
    Writes a live command file that Export.lua can read to update interval dynamically.
    This allows changing the interval WITHOUT restarting DCS!
    """
    interval_seconds = interval_ms / 1000.0

    # Try to find DCS Scripts folder if not provided
    if not scripts_dir:
        scripts_dir = find_dcs_scripts_folder()

    if not scripts_dir:
        logger.warning("Cannot write live command: DCS Scripts folder not found")
        return

    command_path = os.path.join(scripts_dir, 'forwarder_command.json')

    try:
        command_data = {
            "updateInterval": interval_seconds,
            "timestamp": datetime.now().isoformat()
        }
        with open(command_path, 'w', encoding='utf-8') as f:
            json.dump(command_data, f, indent=2)
        logger.info(f"✅ Live command sent: UPDATE_INTERVAL → {interval_seconds}s (DCS will update within 2 seconds)")
    except Exception as e:
        logger.warning(f"Failed to write live command: {e}")


def update_export_lua_interval(interval_ms: int, lua_path: str):
    """
    Updates the UPDATE_INTERVAL in the specified Export.lua file.
    """
    if not os.path.exists(lua_path):
        logger.warning(f"Export.lua not found at {lua_path}, cannot update interval.")
        return

    interval_seconds = interval_ms / 1000.0

    try:
        with open(lua_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        updated = False
        new_lines = []
        # Regex to find 'local UPDATE_INTERVAL = 0.2' (or other numbers)
        pattern = re.compile(r"(local\s+UPDATE_INTERVAL\s*=\s*)[\d.]+")

        for line in lines:
            new_line, count = pattern.subn(r"\g<1>" + str(interval_seconds), line)
            if count > 0:
                new_lines.append(new_line)
                updated = True
            else:
                new_lines.append(line)

        if updated:
            # Safely write back to the file
            temp_path = lua_path + '.tmp'
            with open(temp_path, 'w', encoding='utf-8') as f:
                f.writelines(new_lines)
            os.replace(temp_path, lua_path)
            logger.info(f"Updated UPDATE_INTERVAL in {os.path.basename(lua_path)} to {interval_seconds} seconds (requires DCS restart).")


    except Exception as e:
        logger.error(f"Failed to update {os.path.basename(lua_path)}: {e}")


def main(argv=None):
    p = argparse.ArgumentParser(description='Forward parsed JSONL as UDP datagrams with ECDH encryption (PSK mode removed)')
    p.add_argument('--file', '-f', default=DEFAULT_FILE, help='Path to JSONL file')
    p.add_argument('--use-export', action='store_true', help='Auto-detect and use export.lua-generated JSON in DCS Saved Games Scripts folder')
    p.add_argument('--scripts-dir', default=None, help='Override path to DCS Scripts directory for auto-detection')
    p.add_argument('--host', default=DEFAULT_HOST, help='Destination host')
    p.add_argument('--port', '-p', type=int, default=DEFAULT_PORT, help='Destination port')
    p.add_argument('--bind-ip', default='127.0.0.1',
                   help='IP address to bind to for ECDH handshakes (default: 127.0.0.1 for localhost only). '
                        'Use 0.0.0.0 to bind to all interfaces (INSECURE - requires confirmation)')
    p.add_argument('--handshake-port', type=int, default=None,
                   help='Port to listen for ECDH handshakes (default: same as --port). '
                        'Use different port when sender and receiver are on same PC.')
    p.add_argument('--interval', type=int, default=200, help='Polling interval in milliseconds (e.g., 50 for 50ms).')
    p.add_argument('--verbose', '-v', action='store_true', help='Verbose output')
    p.add_argument('--repeat-last', action='store_true', help='Repeat the last line every <interval> milliseconds')
    p.add_argument('--show-env', action='store_true', help='Print temperature/pressure/wind when sending')
    p.add_argument('--authorized-devices', default='authorized_devices.json', help='Path to authorized devices file')
    p.add_argument('--aircraft', default=None, help='Aircraft name to send in handshake')
    p.add_argument('--export-lua-path', default=None, help='Path to Export.lua to update interval. If not provided, will search in script folder.')
    p.add_argument('--no-update-lua', action='store_true', help='Do not attempt to update Export.lua.')
    args = p.parse_args(argv)

    # Setup logging
    log_level = logging.INFO if args.verbose else logging.WARNING
    logging.basicConfig(
        level=log_level,
        format='%(asctime)s [%(levelname)s] %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )

    # Update Export.lua if requested
    if not args.no_update_lua:
        lua_path = args.export_lua_path
        if not lua_path:
            script_dir = os.path.dirname(os.path.abspath(__file__))
            lua_path = os.path.join(script_dir, 'Export.lua')

        if os.path.exists(lua_path):
            update_export_lua_interval(args.interval, lua_path)
        else:
            logger.warning(f"Export.lua not found at '{lua_path}'. Searching in other locations.")
            # Try to find it near the --file location, if --use-export was used
            if getattr(args, 'use_export', False) or 'DCS' in args.file:
                file_dir = os.path.dirname(args.file)
                lua_path_alt = os.path.join(file_dir, 'Export.lua')
                if os.path.exists(lua_path_alt):
                    logger.info(f"Found Export.lua in data file directory: {lua_path_alt}")
                    update_export_lua_interval(args.interval, lua_path_alt)
                else:
                    logger.warning(f"Could not find Export.lua in {file_dir} either. Interval not updated.")
            else:
                logger.warning("Not a DCS export path, not searching further. Interval not updated.")

        # LIVE COMMAND: Write command file for runtime interval updates (no DCS restart needed!)
        scripts_dir = None
        if 'DCS' in args.file or getattr(args, 'use_export', False):
            scripts_dir = os.path.dirname(args.file)
        write_live_command(args.interval, scripts_dir)

    
    # Auto-detect DCS export file if requested (--use-export)
    if getattr(args, 'use_export', False):
        scripts_dir = args.scripts_dir
        if not scripts_dir:
            scripts_dir = find_dcs_scripts_folder()
        if scripts_dir:
            found = find_export_file(scripts_dir)
            if found:
                args.file = found
                print(f"🔎 Auto-detected export file: {args.file}")
            else:
                print("⚠️ No export JSON file found in DCS Scripts folder; continuing with specified/default file")
        else:
            print("⚠️ Could not locate DCS Scripts folder; continuing with specified/default file")

    # Check ECDH mode requirements
    if not HANDSHAKE_AVAILABLE:
        print("❌ Error: crypto_handshake.py not found", file=sys.stderr)
        print("   Make sure crypto_handshake.py is in the same directory", file=sys.stderr)
        return 2

    print("🔐 ECDH Handshake Mode (PSK removed)")
    print(f"📂 Authorized devices: {args.authorized_devices}")

    # Security check: warn if binding to all interfaces
    check_bind_security(args.bind_ip)

    session_mgr = SessionManager(
        authorized_devices_path=args.authorized_devices,
        aircraft_name=args.aircraft
    )

    enc_status = "🔒 ECDH-AES-GCM"
    
    interval_seconds = args.interval / 1000.0
    
    try:
        if args.repeat_last:
            print(f"Repeating last line every {args.interval} ms from {args.file} to {args.host}:{args.port} ({enc_status})")
            repeat_last_line(args.file, args.host, args.port, session_mgr, interval=interval_seconds, verbose=args.verbose,
                           show_env=args.show_env, handshake_port=args.handshake_port, bind_ip=args.bind_ip)
        else:
            print(f"Forwarding {args.file} to {args.host}:{args.port} (forward only new lines) ({enc_status})")
            while True:
                try:
                    tail_and_send(args.file, args.host, args.port, session_mgr, send_existing=False, once=False,
                                interval=interval_seconds, verbose=args.verbose, show_env=args.show_env,
                                handshake_port=args.handshake_port, bind_ip=args.bind_ip)
                except KeyboardInterrupt:
                    raise
                except FileNotFoundError:
                    print(f"File not found: {args.file}")
                    time.sleep(5)
                    continue
                except Exception:
                    import traceback
                    print("Unhandled error in tail_and_send, restarting in 5s:", file=sys.stderr)
                    traceback.print_exc()
                    time.sleep(5)
                    continue
    except FileNotFoundError:
        print(f"File not found: {args.file}")
        return 2
    except KeyboardInterrupt:
        print("Interrupted")
    finally:
        # Cleanup session manager
        if session_mgr:
            session_mgr.stop_cleanup_thread()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
